// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoLES.Server.Data;

#nullable disable

namespace ProjetoLES.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315182122_ProductsAndStock")]
    partial class ProductsAndStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ProjetoLES.Server.Models.CardBrandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("CardBrands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Visa",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Mastercard",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Elo",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "American Express",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hipercard",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hiper",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000006")
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diners Club",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000007")
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cabal",
                            Uuid = new Guid("22222222-0000-4000-8000-000000000008")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Medicamentos em geral",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Medicamentos",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Description = "Analgésicos e antitérmicos",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dor e Febre",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            Description = "Saúde e bem-estar",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bem-estar",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            Description = "Antialérgicos",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Alergia",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            Id = 5,
                            Description = "Saúde digestiva",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Digestivo",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vitaminas e suplementos",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Vitaminas",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000006")
                        },
                        new
                        {
                            Id = 7,
                            Description = "Higiene pessoal",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Higiene",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000007")
                        },
                        new
                        {
                            Id = 8,
                            Description = "Cosméticos e cuidados com a pele",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dermocosméticos",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000008")
                        },
                        new
                        {
                            Id = 9,
                            Description = "Antibióticos e antimicrobianos",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Antibióticos",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000009")
                        },
                        new
                        {
                            Id = 10,
                            Description = "Medicamentos sob prescrição médica",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tarja Vermelha",
                            Uuid = new Guid("33333333-0000-4000-8000-000000000010")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CreditCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrintedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("CardBrandId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("CreditCards", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerAddressModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerPhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("CustomerPhones", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.DrugInteractionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("ProductBId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.HasIndex("ProductAId", "ProductBId")
                        .IsUnique();

                    b.ToTable("DrugInteractions", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.PricingGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitMarginPercent")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("PricingGroups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Margem padrão de 30%",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Padrão",
                            ProfitMarginPercent = 30m,
                            Uuid = new Guid("44444444-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Description = "Margem de 50% para produtos premium",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Premium",
                            ProfitMarginPercent = 50m,
                            Uuid = new Guid("44444444-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            Description = "Margem reduzida de 20% para genéricos",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Genérico",
                            ProfitMarginPercent = 20m,
                            Uuid = new Guid("44444444-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            Description = "Margem de 40% para suplementos e vitaminas",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Suplemento",
                            ProfitMarginPercent = 40m,
                            Uuid = new Guid("44444444-0000-4000-8000-000000000004")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductCategoryModel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 10
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 5
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivePrinciple")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DepthCm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InactivationCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriptionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricingGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.Property<decimal?>("WeightGrams")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("PricingGroupId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivePrinciple = "Paracetamol 750mg",
                            Barcode = "7891234000001",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Indicado para alívio de dores leves a moderadas e redução da febre.",
                            ImageUrl = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Paracetamol 750mg",
                            PrescriptionType = 0,
                            PricingGroupId = 3,
                            ProductCode = "PROD0001",
                            SalePrice = 18.90m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            ActivePrinciple = "Ibuprofeno 600mg",
                            Barcode = "7891234000002",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anti-inflamatório não esteroidal para dores musculares e febre.",
                            ImageUrl = "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ibuprofeno 600mg",
                            PrescriptionType = 0,
                            PricingGroupId = 3,
                            ProductCode = "PROD0002",
                            SalePrice = 22.50m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            ActivePrinciple = "Amoxicilina Tri-hidratada 500mg",
                            Barcode = "7891234000003",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Antibiótico indicado para tratamento de infecções bacterianas.",
                            ImageUrl = "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Amoxicilina 500mg",
                            PrescriptionType = 2,
                            PricingGroupId = 1,
                            ProductCode = "PROD0003",
                            SalePrice = 35.00m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            ActivePrinciple = "Dipirona Sódica 1g",
                            Barcode = "7891234000004",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Analgésico e antitérmico indicado para dores e febre.",
                            ImageUrl = "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dipirona 1g",
                            PrescriptionType = 0,
                            PricingGroupId = 3,
                            ProductCode = "PROD0004",
                            SalePrice = 15.75m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            Id = 5,
                            ActivePrinciple = "Loratadina 10mg",
                            Barcode = "7891234000005",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Antialérgico indicado para rinite, urticária e outras alergias.",
                            ImageUrl = "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Loratadina 10mg",
                            PrescriptionType = 0,
                            PricingGroupId = 3,
                            ProductCode = "PROD0005",
                            SalePrice = 27.30m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            Id = 6,
                            ActivePrinciple = "Omeprazol 20mg",
                            Barcode = "7891234000006",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduz a produção de ácido no estômago, indicado para gastrite e refluxo.",
                            ImageUrl = "https://images.unsplash.com/photo-1550572017-4fade5817617?w=400&h=400&fit=crop&q=80",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Omeprazol 20mg",
                            PrescriptionType = 0,
                            PricingGroupId = 3,
                            ProductCode = "PROD0006",
                            SalePrice = 19.90m,
                            UpdatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Uuid = new Guid("66666666-0000-4000-8000-000000000006")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductStockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("ProductStocks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 5,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 0,
                            BlockedQuantity = 0,
                            IsDeleted = false,
                            LastUpdated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Uuid = new Guid("77777777-0000-4000-8000-000000000006")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Administrador do sistema",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin",
                            Uuid = new Guid("11111111-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Description = "Funcionário",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Employee",
                            Uuid = new Guid("11111111-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cliente",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Customer",
                            Uuid = new Guid("11111111-0000-4000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.StockEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("StockEntries", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.SupplierModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cnpj = "57.507.378/0001-41",
                            ContactEmail = "comercial@ems.com.br",
                            ContactPhone = "11999990001",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "EMS Sigma Pharma",
                            Uuid = new Guid("55555555-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = 2,
                            Cnpj = "61.190.096/0001-92",
                            ContactEmail = "vendas@eurofarma.com.br",
                            ContactPhone = "11999990002",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Eurofarma",
                            Uuid = new Guid("55555555-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = 3,
                            Cnpj = "02.932.074/0001-91",
                            ContactEmail = "pedidos@hypermarcas.com.br",
                            ContactPhone = "11999990003",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hypermarcas",
                            Uuid = new Guid("55555555-0000-4000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.UserRoleModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CreditCardModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CardBrandModel", "CardBrand")
                        .WithMany("CreditCards")
                        .HasForeignKey("CardBrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoLES.Server.Models.CustomerModel", "Customer")
                        .WithMany("CreditCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardBrand");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerAddressModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CustomerModel", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerPhoneModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CustomerModel", "Customer")
                        .WithMany("Phones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.DrugInteractionModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.ProductModel", "ProductA")
                        .WithMany("InteractionsAsSource")
                        .HasForeignKey("ProductAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLES.Server.Models.ProductModel", "ProductB")
                        .WithMany("InteractionsAsTarget")
                        .HasForeignKey("ProductBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductA");

                    b.Navigation("ProductB");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductCategoryModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CategoryModel", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLES.Server.Models.ProductModel", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.PricingGroupModel", "PricingGroup")
                        .WithMany("Products")
                        .HasForeignKey("PricingGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PricingGroup");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductStockModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.ProductModel", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("ProjetoLES.Server.Models.ProductStockModel", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.StockEntryModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.ProductModel", "Product")
                        .WithMany("StockEntries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLES.Server.Models.SupplierModel", "Supplier")
                        .WithMany("StockEntries")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.TransactionModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CreditCardModel", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoLES.Server.Models.CustomerModel", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.UserModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.CustomerModel", "Customer")
                        .WithOne("User")
                        .HasForeignKey("ProjetoLES.Server.Models.UserModel", "CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.UserRoleModel", b =>
                {
                    b.HasOne("ProjetoLES.Server.Models.RoleModel", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoLES.Server.Models.UserModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CardBrandModel", b =>
                {
                    b.Navigation("CreditCards");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CategoryModel", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.CustomerModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CreditCards");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.PricingGroupModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.ProductModel", b =>
                {
                    b.Navigation("InteractionsAsSource");

                    b.Navigation("InteractionsAsTarget");

                    b.Navigation("ProductCategories");

                    b.Navigation("Stock");

                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.RoleModel", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.SupplierModel", b =>
                {
                    b.Navigation("StockEntries");
                });

            modelBuilder.Entity("ProjetoLES.Server.Models.UserModel", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
